spring:
  datasource:
    driver-class-name: org.h2.Driver
    generate-unique-name: false
    url: jdbc:h2:./H2/spring-h2
    username: spring
    password: springpass
  sql:
    init-mode: always
    init:
      enabled: true
  h2:
    console:
      enabled: true